//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.12.24 at 02:13:04 PM IST 
//


package com.backend.unfound.xmlparser;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for vehicleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="vehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;enumeration value="vehicle 1"/>
 *               &lt;enumeration value="vehicle 2"/>
 *               &lt;enumeration value="vehicle 3"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="frame" type="{}frameType"/>
 *         &lt;element name="wheels" type="{}wheelsType"/>
 *         &lt;element name="powertrain" type="{}powertrainType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "vehicleType", propOrder = {
    "id",
    "frame",
    "wheels",
    "powertrain"
})
public class VehicleType {

    @XmlElement(required = true)
    protected String id;
    @XmlElement(required = true)
    protected FrameType frame;
    @XmlElement(required = true)
    protected WheelsType wheels;
    @XmlElement(required = true)
    protected PowertrainType powertrain;

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the frame property.
     * 
     * @return
     *     possible object is
     *     {@link FrameType }
     *     
     */
    public FrameType getFrame() {
        return frame;
    }

    /**
     * Sets the value of the frame property.
     * 
     * @param value
     *     allowed object is
     *     {@link FrameType }
     *     
     */
    public void setFrame(FrameType value) {
        this.frame = value;
    }

    /**
     * Gets the value of the wheels property.
     * 
     * @return
     *     possible object is
     *     {@link WheelsType }
     *     
     */
    public WheelsType getWheels() {
        return wheels;
    }

    /**
     * Sets the value of the wheels property.
     * 
     * @param value
     *     allowed object is
     *     {@link WheelsType }
     *     
     */
    public void setWheels(WheelsType value) {
        this.wheels = value;
    }

    /**
     * Gets the value of the powertrain property.
     * 
     * @return
     *     possible object is
     *     {@link PowertrainType }
     *     
     */
    public PowertrainType getPowertrain() {
        return powertrain;
    }

    /**
     * Sets the value of the powertrain property.
     * 
     * @param value
     *     allowed object is
     *     {@link PowertrainType }
     *     
     */
    public void setPowertrain(PowertrainType value) {
        this.powertrain = value;
    }

}
